### ISSUE TITLE
soularr.py permission denied

### ISSUE THREAD

**Issue by fedorapenguin** [mrusse/soularr#105]
This is running under a docker container and this is the output from docker logs, i have added the path and api key to the config.ini template, haven't changed anything else
```
PermissionError: [Errno 13] Permission denied: '/data/.current_page.txt'
29/03/2025 09:38:49 - Waiting for 300 seconds before checking again...
Traceback (most recent call last):
  File "/app/soularr.py", line 733, in <module>
    wanted_records.extend(get_records(missing))
                          ^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 609, in get_records
    page = get_current_page(current_page_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 578, in get_current_page
    with open(path, 'w') as file:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/data/.current_page.txt'
```

**Comment by insanemal** [comment]
Yeah it doesn't have permission to write into whatever is mounted at /data. 

Check your permissions.

**Comment by lvleph** [comment]
It isn't intended that you blindly use the docker-compose. You will need to figure out your UID (`id -u`) and GID (`id -g`) and replace the values in `user:` section with the values from the output of those commands. It should look like `user: UID:GID`. This goes for both solarr and slskd containers.

**Comment by fedorapenguin** [comment]
> It isn't intended that you blindly use the docker-compose. You will need to figure out your UID (`id -u`) and GID (`id -g`) and replace the values in `user:` section with the values from the output of those commands. It should look like `user: UID:GID`. This goes for both solarr and slskd containers.
> 
> That being said it is hard to debug without seeing those compose files and then the output from the commands I posted.

```
services:
  soularr:
    restart: unless-stopped
    container_name: soularr
    hostname: soularr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolakata
      #Script interval in seconds
      - SCRIPT_INTERVAL=300
    user: "1000:1000"
    volumes:
      #"You can set /downloads to whatever you want but will then need to change the Slskd download dir in your config file"
      - /mnt/drive/slskd:/downloads
      #Select where you are storing your config file. 
      #Leave "/data" since thats where the script expects the config file to be
      - ../config:/data
    image: mrusse08/soularr:latest
```


The compose file is as pasted above, id -u and ig -g also return 1000 as is in the configuration, therefore eliminating the need for a change there. Please do let me know if there are any other commands i can run to help you diagnose the issue, thank you.

**Comment by insanemal** [comment]
This tells us the soularr config not the slskd or readarr config. 

Or what the effective permissions on /mnt/drive/slskd are.

But I guess it's a start

**Comment by fedorapenguin** [comment]
> This tells us the soularr config not the slskd or readarr config.
> 
> Or what the effective permissions on /mnt/drive/slskd are.
> 
> But I guess it's a start

slskd.yml:
```
shares:
  directories:
    - /mnt/drive/lidarr
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
  cache:
    storage_mode: memory
    workers: 16
    retention: ~ # retain indefinitely (do not automatically re-scan)
global:
  upload:
    slots: 20
    speed_limit: 3000 # in kibibytes
  limits:
    queued:
      files: 500
      megabytes: 5000
    daily:
      files: 1000
      megabytes: 10000
      failures: 200
    weekly:
      files: 5000
      megabytes: 50000
      failures: 1000
  download:
    slots: 500
    speed_limit: 1000
web:
  port: 5030
  https:
    disabled: false
    port: 5031
    force: false
    certificate:
      pfx: ~
      password: ~
  url_base: /
  content_path: wwwroot
  logging: false
  authentication:
    disabled: false
    username: slskd
    password: slskd
    jwt:
      key: ~
      ttl: 604800000
    api_keys:
      my_api_key:
        key: REDACTED
        role: readwrite # readonly, readwrite, administrator
        cidr: 0.0.0.0/0,::/0
soulseek:
  address: vps.slsknet.org
  port: 2271
  username: REDACTED
  password: REDACTED
```

slskd docker compose:
```
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - PUID=1000
      - PGID=1000
    user: "1000:1000"
    volumes:
      - ../config:/app
      - /mnt/drive/slskd:/app/downloads
      - /mnt/drive/lidarr:/mnt/doomnas/lidarr:ro #for soulseek share
    restart: always
```

As for the permissions:
```
❯ ls -ld slskd
drwxrwxrwx 1 root root 0 Mar 29 15:54 slskd
❯ ls -ld lidarr
drwxrwxrwx 1 root root 0 Mar 29 15:59 lidarr

For both the config directories:
drwxr-xr-x 1 root   root     54 Mar 30 09:39 config
Only the folder creation date and the number before it (folder size?) varies.
 ```
