### ISSUE TITLE
Wrong directories? Lidarr not importing on download completion

### ISSUE THREAD

**Issue by jmbannon** [mrusse/soularr#42]
Hello, this is most likely a user-error but I'm hoping for guidance on how to properly set up folders to get Lidar imports working.

Docker Compose:
```
  lidarr:
    volumes:
      - ${NAS_PATH}/Downloads/slskd/complete:/downloads
  soularr:
    volumes:
      - ${NAS_PATH}/Downloads/slskd/complete:/downloads
  slskd:
    volumes:
      - ${NAS_PATH}/Downloads/slskd:/downloads
```

Soularr Config:
```
[Lidarr]
download_dir = /downloads
[Slskd]
download_dir = /downloads
```

Slskd Config:
```
directories:
  incomplete: /downloads/incomplete
  downloads: /downloads/complete
```

My thinking is
1) Slskd downloads into `/downloads/complete` [`${NAS_PATH}/Downloads/slskd/complete`]
2) soularr sees this in `/downloads` [`${NAS_PATH}/Downloads/slskd/complete`]
3) soularr tells Lidarr to import from `/downloads` [`${NAS_PATH}/Downloads/slskd/complete`]

So far no luck, and no actionable messages from the logs. Any clarity on this would be appreciated. Thanks for this great script!
