### ISSUE TITLE
Soularr reports tracks finished downloading but nothing downloads in slskd

### ISSUE THREAD

**Issue by vfedetz** [mrusse/soularr#46]
Soularr executes the slskd searches for wanted albums from Lidarr (can see them in the slskd UI). However the albums never show as downloading in slskd UI, and Soularr exists after logging that "all tracks finished downloading".

```
[INFO|soularr|L335] 2024-11-30T09:37:38-0500: -------------------
[INFO|soularr|L336] 2024-11-30T09:37:38-0500: Waiting for downloads... monitor at: https://soulseek.local.kanvisuals.net/downloads
[INFO|soularr|L367] 2024-11-30T09:37:38-0500: All tracks finished downloading!
[INFO|soularr|L626] 2024-11-30T09:37:43-0500: Solarr finished. Exiting...
30/11/2024 09:37:44 - Waiting for 300 seconds before checking again...
```

**Comment by vfedetz** [comment]
```
$ cat config.ini
[Lidarr]
api_key = REDACTED
host_url = https://lidarr.local.REDACTED.net
# as configured in lidarr docker compose
download_dir = /downloads

[Slskd]
api_key = REDACTED
host_url = https://soulseek.local.REDACTED.net
# as configured in soularr docker compose
download_dir = /downloads
delete_searches = True
stalled_timeout = 3600

[Release Settings]
use_most_common_tracknum = True
allow_multi_disc = True
accepted_countries = Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada
accepted_formats = CD,Digital Media

[Search Settings]
search_timeout = 5000
maximum_peer_queue = 50
minimum_peer_upload_speed = 0
allowed_filetypes = flac
ignored_users = User1,User2,Fred,Bob
search_for_tracks = False
album_prepend_artist = True
track_prepend_artist = True
search_type = incrementing_page
number_of_albums_to_grab = 10
remove_wanted_on_failure = False
title_blacklist = BlacklistWord1,blacklistword2

[Logging]
level = INFO
# https://docs.python.org/3/library/logging.html#logrecord-attributes
format = [%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s
# https://docs.python.org/3/library/time.html#time.strftime
datefmt = %Y-%m-%dT%H:%M:%S%z
```

Lidarr docker-compose excerpt
`/mnt/data/downloads/soulseek/complete:/downloads`

Slskd docker-compose excerpt
```
SLSKD_DOWNLOADS_DIR=/downloads/complete
SLSKD_INCOMPLETE_DIR=/downloads/incomplete
/mnt/data/downloads/soulseek:/downloads
```
Soularr docker-compose
```
  soularr:
    restart: unless-stopped
    container_name: soularr
    hostname: soularr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      #Script interval in seconds
      - SCRIPT_INTERVAL=300
    user: "1000:1000"
    volumes:
      #"You can set /downloads to whatever you want but will then need to change the Slskd download dir in your config file"
      - /mnt/data/downloads/soulseek/complete:/downloads
      #Select where you are storing your config file. 
      #Leave "/data" since thats where the script expects the config file to be
      - /home/vfedetz/docker/soularr:/data
    image: mrusse08/soularr:latest
```
