### ISSUE TITLE
Support: I feel stupid - soulseek API

### ISSUE THREAD

**Issue by alternativesurfer** [mrusse/soularr#85]
My brain isn't working today.....
I run soulseek via docker, and have no idea what I need to add to my compose file in order to satisfy this:

![Image](https://github.com/user-attachments/assets/a50d1f5d-92c8-45c7-a66b-f3653f89eb3f)

**Comment by mrusse** [comment]
You just need to come up with an API key (either just randomly smash on your keyboard or use a password generator or something). And put it in the slskd.yml file. The link in the readme shows an example. 

```yml
web:
  authentication:
    disabled: false
    username: slskd
    password: slskd
    jwt:
      key: ~
      ttl: 604800000
    api_keys:
      my_api_key:
        key: <some example string between 16 and 255 characters>
        cidr: 0.0.0.0/0,::/0
```

Please either use the discusions or join the discord for troubleshooting help. This is not an issue. Thank you.
