### ISSUE TITLE
Import failed when completion

### ISSUE THREAD

**Issue by Rollbacke** [mrusse/soularr#93]
Hi,

I think it's just a configuration issue, but I admit I don't see where.

`docker-compose.yml`:
```
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    env_file:
      - "./arr/data/lidarr/.env"
    volumes:
      - ./arr/data/lidarr/config/:/config/:rw
      - /mnt/nas/musiques/Indexed_Musique/Hi-Res/:/nas/:rw
      - /mnt/nas-fstab/downloads/soulseek/:/soulseek/:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      net_bridge:
    restart: unless-stopped

  soulseek:
    container_name: soulseek
    image: slskd/slskd:latest
    env_file:
      - "./arr/data/soulseek/.env"
    ports:
      - 50300:50300/tcp
    volumes:
      - ./arr/data/soulseek/config/:/app/:rw
      - /mnt/nas-fstab/musiques/Indexed_musique/Hi-Res:/nas/:rw
      - /mnt/nas-fstab/downloads/soulseek/:/soulseek/:rw
    user: 1015:1002
    networks:
      net_bridge:
    restart: unless-stopped

  soularr:
    container_name: soularr
    image: mrusse08/soularr:latest
    env_file:
      - "./arr/data/soularr/.env"
    user: "1018:1002"
    volumes:
      - ./arr/data/soularr/config/:/data/:rw
      - /mnt/nas-fstab/downloads/soulseek/:/soulseek/:rw
    networks:
      net_bridge:
    restart: unless-stopped
```

Soularr config:
```
[Lidarr]
api_key = xxx
host_url = http://lidarr:8686
download_dir = /soulseek/

[Slskd]
api_key = xxx
host_url = http://soulseek:5030
download_dir = /soulseek/
delete_searches = True
stalled_timeout = 3600

[Release Settings]
use_most_common_tracknum = True
allow_multi_disc = True
accepted_countries = Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada
accepted_formats = CD,Digital Media,Vinyl

[Search Settings]
search_timeout = 5000
maximum_peer_queue = 50
minimum_peer_upload_speed = 0
minimum_filename_match_ratio = 0.5
allowed_filetypes = flac 24/192,flac 16/44.1,flac
search_for_tracks = False
album_prepend_artist = True
track_prepend_artist = True
  #"all" will search for every wanted record everytime soularr is run.
  #"incrementing_page" will start with the first page and increment to the next on each run.
  #"first_page" will repeatedly search the first page.
search_type = incrementing_page
number_of_albums_to_grab = 10
remove_wanted_on_failure = False
search_source = missing

[Logging]
level = INFO
format = [%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s
datefmt = %Y-%m-%dT%H:%M:%S%z
```

When I add an missing album, the download is started, but, when completion occur:

```
soularr  | [INFO|soularr|L438] 2025-02-23T21:00:35+0100: All tracks finished downloading!                                                                                                                                                                                                                                                                                   
soularr  | [INFO|soularr|L509] 2025-02-23T21:00:41+0100: Starting Lidarr import for: downloading ID: 15426                                                                                                                                                                                                                                                                  
soularr  | [INFO|soularr|L509] 2025-02-23T21:00:41+0100: Starting Lidarr import for: complete ID: 15427                                                                                                                                                                                                                                                                     
soularr  | [INFO|soularr|L524] 2025-02-23T21:00:43+0100: Downloaded Albums Scan Failed to import from: /soulseek/downloading                                                                                                                                                                                                                                                
soularr  | [INFO|soularr|L551] 2025-02-23T21:00:43+0100: Failed import moved to: failed_imports/downloading                                                                                                                                                                                                                                                                 
soularr  | [INFO|soularr|L524] 2025-02-23T21:00:43+0100: Downloaded Albums Scan Failed to import from: /soulseek/complete                                                                                                                                                                                                                                                   
soularr  | [INFO|soularr|L551] 2025-02-23T21:00:43+0100: Failed import moved to: failed_imports/complete                                                                                                                                                                                                                                                                    
soularr  | [INFO|soularr|L750] 2025-02-23T21:00:43+0100: Soularr finished. Exiting...
```

I can't find anything usefull in Lidarr logs...

Thanks in advance.
